[package]
name = "stonedb"
version = "0.1.0"
edition = "2024"

[dependencies]
bson = "3.0.0"
fslock = "0.2.1"
memory-stats = "1.2.0"
regex = "1.11.3"
tokio = { version = "1.47.1", features = ["full"] }
toml = "0.9.7"
